// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetClipboarText():Promise<string>;

export function GetClipsAfter(arg1:string):Promise<Array<main.Clip>>;

export function GetCurrentTime():Promise<string>;

export function GetLatestClips(arg1:number,arg2:number):Promise<Array<main.Clip>>;

export function RemoveClip(arg1:number):Promise<void>;

export function SaveClip(arg1:string):Promise<number>;

export function SetClipboarText(arg1:string):Promise<void>;
