// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboarText() {
  return window['go']['main']['App']['GetClipboarText']();
}

export function GetClipsAfter(arg1) {
  return window['go']['main']['App']['GetClipsAfter'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetLatestClips(arg1, arg2) {
  return window['go']['main']['App']['GetLatestClips'](arg1, arg2);
}

export function HideApplication() {
  return window['go']['main']['App']['HideApplication']();
}

export function PreventCopyText(arg1) {
  return window['go']['main']['App']['PreventCopyText'](arg1);
}

export function RemoveClip(arg1) {
  return window['go']['main']['App']['RemoveClip'](arg1);
}

export function SaveClip(arg1) {
  return window['go']['main']['App']['SaveClip'](arg1);
}

export function SetClipboarText(arg1) {
  return window['go']['main']['App']['SetClipboarText'](arg1);
}
